[package]
name = "decaf377"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
hex = "0.4"
num-bigint = "0.4"
once_cell = "1.8"
tracing = "0.1"
tracing-subscriber = "0.2"
ark-relations = "0.3"
ark-r1cs-std = "0.3"
ark-std = "0.3"
ark-ec = "0.3"
ark-ff = "0.3"
ark-serialize = "0.3"
ark-ed-on-bls12-377 = { git = "https://github.com/arkworks-rs/curves", rev = "677b4ae751a274037880ede86e9b6f30f62635af" }
ark-bls12-377 = { git = "https://github.com/arkworks-rs/curves", default-features = false, features = ["curve"], rev = "677b4ae751a274037880ede86e9b6f30f62635af" }
zeroize = "1.4"
jf-plonk = { git = "https://github.com/EspressoSystems/jellyfish", optional=true }

[features]
proofs = ["jf-plonk"]

[dev-dependencies]
proptest = "1"

[patch.crates-io]
# The "ours" branch is based off of v0.3.0
ark-ff = { git = "https://github.com/penumbra-zone/algebra", branch = "ours" }
ark-serialize = { git = "https://github.com/penumbra-zone/algebra", branch = "ours" }
